import { DataTypes, ListaMoedasTypes, MoedaDataTypes } from "../types/types";

export function formataMonetario(valor: number) {
  return valor.toFixed(2).replace(".", ",");
}

export const listaMoedas: ListaMoedasTypes[] = [
  { label: "Dólar Americano/Real Brasileiro", value: "USD-BRL" },
  { label: "Dólar Americano/Real Brasileiro Turismo", value: "USD-BRLT" },
  { label: "Dólar Canadense/Real Brasileiro", value: "CAD-BRL" },
  { label: "Euro/Real Brasileiro", value: "EUR-BRL" },
  { label: "Libra Esterlina/Real Brasileiro", value: "GBP-BRL" },
  { label: "Peso Argentino/Real Brasileiro", value: "ARS-BRL" },
  { label: "Bitcoin/Real Brasileiro", value: "BTC-BRL" },
  { label: "Litecoin/Real Brasileiro", value: "LTC-BRL" },
  { label: "Iene Japonês/Real Brasileiro", value: "JPY-BRL" },
  { label: "Franco Suíço/Real Brasileiro", value: "CHF-BRL" },
  { label: "Dólar Australiano/Real Brasileiro", value: "AUD-BRL" },
  { label: "Yuan Chinês/Real Brasileiro", value: "CNY-BRL" },
  { label: "Novo Shekel Israelense/Real Brasileiro", value: "ILS-BRL" },
  { label: "Ethereum/Real Brasileiro", value: "ETH-BRL" },
  { label: "XRP/Real Brasileiro", value: "XRP-BRL" },
  { label: "Dogecoin/Real Brasileiro", value: "DOGE-BRL" },
  { label: "Dólar de Cingapura/Real Brasileiro", value: "SGD-BRL" },
  { label: "Dirham dos Emirados/Real Brasileiro", value: "AED-BRL" },
  { label: "Coroa Dinamarquesa/Real Brasileiro", value: "DKK-BRL" },
  { label: "Dólar de Hong Kong/Real Brasileiro", value: "HKD-BRL" },
  { label: "Peso Mexicano/Real Brasileiro", value: "MXN-BRL" },
  { label: "Coroa Norueguesa/Real Brasileiro", value: "NOK-BRL" },
  { label: "Dólar Neozelandês/Real Brasileiro", value: "NZD-BRL" },
  { label: "Zlóti Polonês/Real Brasileiro", value: "PLN-BRL" },
  { label: "Riyal Saudita/Real Brasileiro", value: "SAR-BRL" },
  { label: "Coroa Sueca/Real Brasileiro", value: "SEK-BRL" },
  { label: "Baht Tailandês/Real Brasileiro", value: "THB-BRL" },
  { label: "Nova Lira Turca/Real Brasileiro", value: "TRY-BRL" },
  { label: "Dólar Taiuanês/Real Brasileiro", value: "TWD-BRL" },
  { label: "Bolívar Venezuelano/Real Brasileiro", value: "VEF-BRL" },
  { label: "Rand Sul-Africano/Real Brasileiro", value: "ZAR-BRL" },
  { label: "Peso Chileno/Real Brasileiro", value: "CLP-BRL" },
  { label: "Guarani Paraguaio/Real Brasileiro", value: "PYG-BRL" },
  { label: "Peso Uruguaio/Real Brasileiro", value: "UYU-BRL" },
  { label: "Peso Colombiano/Real Brasileiro", value: "COP-BRL" },
  { label: "Sol do Peru/Real Brasileiro", value: "PEN-BRL" },
  { label: "Boliviano/Real Brasileiro", value: "BOB-BRL" },
  { label: "Rublo Russo/Real Brasileiro", value: "RUB-BRL" },
  { label: "Rúpia Indiana/Real Brasileiro", value: "INR-BRL" },
];

export const dadosIniciais: DataTypes = {
  moedas: '',
  moeda1Codigo: '',
  moeda2Codigo: '',
  alta: 0,
  baixa: 0,
  timestamp: '',
  dataCriacao: ''
};

export const dadosIniciaisMoeda: MoedaDataTypes = {
  ask: 0,
  bid: 0,
  code: "",
  codein: "",
  create_date: "",
  high: 0,
  low: 0,
  name: "",
  pctChange: 0,
  timestamp: "",
  varBid: 0
};

export const listaMoedas2 = [
  { label: "Selecione", value: "" },
  { label: "Dólar Americano", value: "USD" },
  { label: "Dólar Americano Turismo", value: "USDT" },
  { label: "Real Brasileiro", value: "BRL" },
  { label: "Real Brasileiro Turismo", value: "BRLT" },
  { label: "Afghani do Afeganistão", value: "AFN" },
  { label: "Dirham dos Emirados", value: "AED" },
  { label: "Lek Albanês", value: "ALL" },
  { label: "Dram Armênio", value: "AMD" },
  { label: "Guilder das Antilhas", value: "ANG" },
  { label: "Kwanza Angolano", value: "AOA" },
  { label: "Peso Argentino", value: "ARS" },
  { label: "Dólar Australiano", value: "AUD" },
  { label: "Manat Azeri", value: "AZN" },
  { label: "Marco Conversível", value: "BAM" },
  { label: "Dólar de Barbados", value: "BBD" },
  { label: "Taka de Bangladesh", value: "BDT" },
  { label: "Lev Búlgaro", value: "BGN" },
  { label: "Dinar do Bahrein", value: "BHD" },
  { label: "Franco Burundinense", value: "BIF" },
  { label: "Dólar de Brunei", value: "BND" },
  { label: "Boliviano", value: "BOB" },
  { label: "Dólar das Bahamas", value: "BSD" },
  { label: "Bitcoin", value: "BTC" },
  { label: "Pula de Botswana", value: "BWP" },
  { label: "Rublo Bielorrusso", value: "BYN" },
  { label: "Dólar de Belize", value: "BZD" },
  { label: "Dólar Canadense", value: "CAD" },
  { label: "Franco Suíço", value: "CHF" },
  { label: "Franco Suíço", value: "CHFRTS" },
  { label: "Peso Chileno", value: "CLP" },
  { label: "Yuan chinês offshore", value: "CNH" },
  { label: "Yuan Chinês", value: "CNY" },
  { label: "Peso Colombiano", value: "COP" },
  { label: "Colón Costarriquenho", value: "CRC" },
  { label: "Peso Cubano", value: "CUP" },
  { label: "Escudo cabo-verdiano", value: "CVE" },
  { label: "Coroa Checa", value: "CZK" },
  { label: "Franco do Djubouti", value: "DJF" },
  { label: "Coroa Dinamarquesa", value: "DKK" },
  { label: "Dogecoin", value: "DOGE" },
  { label: "Peso Dominicano", value: "DOP" },
  { label: "Dinar Argelino", value: "DZD" },
  { label: "Libra Egípcia", value: "EGP" },
  { label: "Birr Etíope", value: "ETB" },
  { label: "Ethereum", value: "ETH" },
  { label: "Euro", value: "EUR" },
  { label: "Dólar de Fiji", value: "FJD" },
  { label: "Libra Esterlina", value: "GBP" },
  { label: "Lari Georgiano", value: "GEL" },
  { label: "Cedi Ganês", value: "GHS" },
  { label: "Dalasi da Gâmbia", value: "GMD" },
  { label: "Franco de Guiné", value: "GNF" },
  { label: "Quetzal Guatemalteco", value: "GTQ" },
  { label: "Dólar de Hong Kong", value: "HKD" },
  { label: "Lempira Hondurenha", value: "HNL" },
  { label: "Kuna Croata", value: "HRK" },
  { label: "Gourde Haitiano", value: "HTG" },
  { label: "Florim Húngaro", value: "HUF" },
  { label: "Rupia Indonésia", value: "IDR" },
  { label: "Novo Shekel Israelense", value: "ILS" },
  { label: "Rúpia Indiana", value: "INR" },
  { label: "Dinar Iraquiano", value: "IQD" },
  { label: "Rial Iraniano", value: "IRR" },
  { label: "Coroa Islandesa", value: "ISK" },
  { label: "Dólar Jamaicano", value: "JMD" },
  { label: "Dinar Jordaniano", value: "JOD" },
  { label: "Iene Japonês", value: "JPY" },
  { label: "Iene Japonês", value: "JPYRTS" },
  { label: "Shilling Queniano", value: "KES" },
  { label: "Som Quirguistanês", value: "KGS" },
  { label: "Riel Cambojano", value: "KHR" },
  { label: "Franco Comorense", value: "KMF" },
  { label: "Won Sul-Coreano", value: "KRW" },
  { label: "Dinar Kuwaitiano", value: "KWD" },
  { label: "Dólar das Ilhas Cayman", value: "KYD" },
  { label: "Tengue Cazaquistanês", value: "KZT" },
  { label: "Kip Laosiano", value: "LAK" },
  { label: "Libra Libanesa", value: "LBP" },
  { label: "Rúpia de Sri Lanka", value: "LKR" },
  { label: "Loti do Lesoto", value: "LSL" },
  { label: "Litecoin", value: "LTC" },
  { label: "Dinar Líbio", value: "LYD" },
  { label: "Dirham Marroquino", value: "MAD" },
  { label: "Leu Moldavo", value: "MDL" },
  { label: "Ariary Madagascarense", value: "MGA" },
  { label: "Denar Macedônio", value: "MKD" },
  { label: "Kyat de Mianmar", value: "MMK" },
  { label: "Mongolian Tugrik", value: "MNT" },
  { label: "Pataca de Macau", value: "MOP" },
  { label: "Ouguiya Mauritana", value: "MRO" },
  { label: "Rúpia Mauriciana", value: "MUR" },
  { label: "Rufiyaa Maldiva", value: "MVR" },
  { label: "Kwacha Malauiana", value: "MWK" },
  { label: "Peso Mexicano", value: "MXN" },
  { label: "Ringgit Malaio", value: "MYR" },
  { label: "Metical de Moçambique", value: "MZN" },
  { label: "Dólar Namíbio", value: "NAD" },
  { label: "Naira Nigeriana", value: "NGN" },
  { label: "Naira Nigeriana", value: "NGNI" },
  { label: "Naira Nigeriana", value: "NGNPARALLEL" },
  { label: "Córdoba Nicaraguense", value: "NIO" },
  { label: "Coroa Norueguesa", value: "NOK" },
  { label: "Rúpia Nepalesa", value: "NPR" },
  { label: "Dólar Neozelandês", value: "NZD" },
  { label: "Rial Omanense", value: "OMR" },
  { label: "Balboa Panamenho", value: "PAB" },
  { label: "Sol do Peru", value: "PEN" },
  { label: "Kina Papua-Nova Guiné", value: "PGK" },
  { label: "Peso Filipino", value: "PHP" },
  { label: "Rúpia Paquistanesa", value: "PKR" },
  { label: "Zlóti Polonês", value: "PLN" },
  { label: "Guarani Paraguaio", value: "PYG" },
  { label: "Rial Catarense", value: "QAR" },
  { label: "Leu Romeno", value: "RON" },
  { label: "Dinar Sérvio", value: "RSD" },
  { label: "Rublo Russo", value: "RUB" },
  { label: "Rublo Russo", value: "RUBTOD" },
  { label: "Rublo Russo", value: "RUBTOM" },
  { label: "Franco Ruandês", value: "RWF" },
  { label: "Riyal Saudita", value: "SAR" },
  { label: "Rúpias de Seicheles", value: "SCR" },
  { label: "Libra Sudanesa", value: "SDG" },
  { label: "DSE", value: "SDR" },
  { label: "Coroa Sueca", value: "SEK" },
  { label: "Dólar de Cingapura", value: "SGD" },
  { label: "Shilling Somaliano", value: "SOS" },
  { label: "Dobra São Tomé/Príncipe", value: "STD" },
  { label: "Colon de El Salvador", value: "SVC" },
  { label: "Libra Síria", value: "SYP" },
  { label: "Lilangeni Suazilandês", value: "SZL" },
  { label: "Baht Tailandês", value: "THB" },
  { label: "Somoni do Tajiquistão", value: "TJS" },
  { label: "TMT", value: "TMT" },
  { label: "Dinar Tunisiano", value: "TND" },
  { label: "Nova Lira Turca", value: "TRY" },
  { label: "Dólar de Trinidad", value: "TTD" },
  { label: "Dólar Taiuanês", value: "TWD" },
  { label: "Shilling Tanzaniano", value: "TZS" },
  { label: "Hryvinia Ucraniana", value: "UAH" },
  { label: "Shilling Ugandês", value: "UGX" },
  { label: "Peso Uruguaio", value: "UYU" },
  { label: "Som Uzbequistanês", value: "UZS" },
  { label: "Bolívar Venezuelano", value: "VEF" },
  { label: "Dong Vietnamita", value: "VND" },
  { label: "Vatu de Vanuatu", value: "VUV" },
  { label: "Franco CFA Central", value: "XAF" },
  { label: "Prata", value: "XAGG" },
  { label: "Brent Spot", value: "XBR" },
  { label: "Dólar do Caribe Oriental", value: "XCD" },
  { label: "Franco CFA Ocidental", value: "XOF" },
  { label: "Franco CFP", value: "XPF" },
  { label: "XRP", value: "XRP" },
  { label: "Riyal Iemenita", value: "YER" },
  { label: "Rand Sul-Africano", value: "ZAR" },
  { label: "Kwacha Zambiana", value: "ZMK" },
  { label: "Dólar Zimbabuense", value: "ZWL" },
  { label: "Ouro", value: "XAU" },
];

export const listaMoedas3 = [
  { label: "Selecione", value: "" },
  { label: "Afghani do Afeganistão", value: "AFN" },
  { label: "Ariary Madagascarense", value: "MGA" },
  { label: "Baht Tailandês", value: "THB" },
  { label: "Balboa Panamenho", value: "PAB" },
  { label: "Birr Etíope", value: "ETB" },
  { label: "Bitcoin", value: "BTC" },
  { label: "Bolívar Venezuelano", value: "VEF" },
  { label: "Boliviano", value: "BOB" },
  { label: "Brent Spot", value: "XBR" },
  { label: "Cedi Ganês", value: "GHS" },
  { label: "Colón Costarriquenho", value: "CRC" },
  { label: "Colon de El Salvador", value: "SVC" },
  { label: "Córdoba Nicaraguense", value: "NIO" },
  { label: "Coroa Checa", value: "CZK" },
  { label: "Coroa Dinamarquesa", value: "DKK" },
  { label: "Coroa Islandesa", value: "ISK" },
  { label: "Coroa Norueguesa", value: "NOK" },
  { label: "Coroa Sueca", value: "SEK" },
  { label: "Dalasi da Gâmbia", value: "GMD" },
  { label: "Denar Macedônio", value: "MKD" },
  { label: "Dinar Argelino", value: "DZD" },
  { label: "Dinar do Bahrein", value: "BHD" },
  { label: "Dinar Iraquiano", value: "IQD" },
  { label: "Dinar Jordaniano", value: "JOD" },
  { label: "Dinar Kuwaitiano", value: "KWD" },
  { label: "Dinar Líbio", value: "LYD" },
  { label: "Dinar Sérvio", value: "RSD" },
  { label: "Dinar Tunisiano", value: "TND" },
  { label: "Dirham dos Emirados", value: "AED" },
  { label: "Dirham Marroquino", value: "MAD" },
  { label: "Dobra São Tomé/Príncipe", value: "STD" },
  { label: "Dogecoin", value: "DOGE" },
  { label: "Dólar Americano", value: "USD" },
  { label: "Dólar Americano Turismo", value: "USDT" },
  { label: "Dólar Australiano", value: "AUD" },
  { label: "Dólar Canadense", value: "CAD" },
  { label: "Dólar das Bahamas", value: "BSD" },
  { label: "Dólar das Ilhas Cayman", value: "KYD" },
  { label: "Dólar de Barbados", value: "BBD" },
  { label: "Dólar de Belize", value: "BZD" },
  { label: "Dólar de Brunei", value: "BND" },
  { label: "Dólar de Cingapura", value: "SGD" },
  { label: "Dólar de Fiji", value: "FJD" },
  { label: "Dólar de Hong Kong", value: "HKD" },
  { label: "Dólar de Trinidad", value: "TTD" },
  { label: "Dólar do Caribe Oriental", value: "XCD" },
  { label: "Dólar Jamaicano", value: "JMD" },
  { label: "Dólar Namíbio", value: "NAD" },
  { label: "Dólar Neozelandês", value: "NZD" },
  { label: "Dólar Taiuanês", value: "TWD" },
  { label: "Dólar Zimbabuense", value: "ZWL" },
  { label: "Dong Vietnamita", value: "VND" },
  { label: "Dram Armênio", value: "AMD" },
  { label: "DSE", value: "SDR" },
  { label: "Escudo cabo-verdiano", value: "CVE" },
  { label: "Ethereum", value: "ETH" },
  { label: "Euro", value: "EUR" },
  { label: "Florim Húngaro", value: "HUF" },
  { label: "Franco Burundinense", value: "BIF" },
  { label: "Franco CFA Central", value: "XAF" },
  { label: "Franco CFA Ocidental", value: "XOF" },
  { label: "Franco CFP", value: "XPF" },
  { label: "Franco Comorense", value: "KMF" },
  { label: "Franco de Guiné", value: "GNF" },
  { label: "Franco do Djubouti", value: "DJF" },
  { label: "Franco Ruandês", value: "RWF" },
  { label: "Franco Suíço", value: "CHF" },
  { label: "Franco Suíço", value: "CHFRTS" },
  { label: "Gourde Haitiano", value: "HTG" },
  { label: "Guarani Paraguaio", value: "PYG" },
  { label: "Guilder das Antilhas", value: "ANG" },
  { label: "Hryvinia Ucraniana", value: "UAH" },
  { label: "Iene Japonês", value: "JPY" },
  { label: "Iene Japonês", value: "JPYRTS" },
  { label: "Kina Papua-Nova Guiné", value: "PGK" },
  { label: "Kip Laosiano", value: "LAK" },
  { label: "Kuna Croata", value: "HRK" },
  { label: "Kwacha Malauiana", value: "MWK" },
  { label: "Kwacha Zambiana", value: "ZMK" },
  { label: "Kwanza Angolano", value: "AOA" },
  { label: "Kyat de Mianmar", value: "MMK" },
  { label: "Lari Georgiano", value: "GEL" },
  { label: "Lek Albanês", value: "ALL" },
  { label: "Lempira Hondurenha", value: "HNL" },
  { label: "Leu Moldavo", value: "MDL" },
  { label: "Leu Romeno", value: "RON" },
  { label: "Lev Búlgaro", value: "BGN" },
  { label: "Libra Egípcia", value: "EGP" },
  { label: "Libra Esterlina", value: "GBP" },
  { label: "Libra Libanesa", value: "LBP" },
  { label: "Libra Síria", value: "SYP" },
  { label: "Libra Sudanesa", value: "SDG" },
  { label: "Lilangeni Suazilandês", value: "SZL" },
  { label: "Litecoin", value: "LTC" },
  { label: "Loti do Lesoto", value: "LSL" },
  { label: "Manat Azeri", value: "AZN" },
  { label: "Marco Conversível", value: "BAM" },
  { label: "Metical de Moçambique", value: "MZN" },
  { label: "Mongolian Tugrik", value: "MNT" },
  { label: "Naira Nigeriana", value: "NGN" },
  { label: "Naira Nigeriana", value: "NGNI" },
  { label: "Naira Nigeriana", value: "NGNPARALLEL" },
  { label: "Nova Lira Turca", value: "TRY" },
  { label: "Novo Shekel Israelense", value: "ILS" },
  { label: "Ouguiya Mauritana", value: "MRO" },
  { label: "Ouro", value: "XAU" },
  { label: "Pataca de Macau", value: "MOP" },
  { label: "Peso Argentino", value: "ARS" },
  { label: "Peso Chileno", value: "CLP" },
  { label: "Peso Colombiano", value: "COP" },
  { label: "Peso Cubano", value: "CUP" },
  { label: "Peso Dominicano", value: "DOP" },
  { label: "Peso Filipino", value: "PHP" },
  { label: "Peso Mexicano", value: "MXN" },
  { label: "Peso Uruguaio", value: "UYU" },
  { label: "Prata", value: "XAGG" },
  { label: "Pula de Botswana", value: "BWP" },
  { label: "Quetzal Guatemalteco", value: "GTQ" },
  { label: "Rand Sul-Africano", value: "ZAR" },
  { label: "Real Brasileiro", value: "BRL" },
  { label: "Real Brasileiro Turismo", value: "BRLT" },
  { label: "Rial Catarense", value: "QAR" },
  { label: "Rial Iraniano", value: "IRR" },
  { label: "Rial Omanense", value: "OMR" },
  { label: "Riel Cambojano", value: "KHR" },
  { label: "Ringgit Malaio", value: "MYR" },
  { label: "Riyal Iemenita", value: "YER" },
  { label: "Riyal Saudita", value: "SAR" },
  { label: "Rublo Bielorrusso", value: "BYN" },
  { label: "Rublo Russo", value: "RUB" },
  { label: "Rublo Russo", value: "RUBTOD" },
  { label: "Rublo Russo", value: "RUBTOM" },
  { label: "Rufiyaa Maldiva", value: "MVR" },
  { label: "Rúpia de Sri Lanka", value: "LKR" },
  { label: "Rúpia Indiana", value: "INR" },
  { label: "Rupia Indonésia", value: "IDR" },
  { label: "Rúpia Mauriciana", value: "MUR" },
  { label: "Rúpia Nepalesa", value: "NPR" },
  { label: "Rúpia Paquistanesa", value: "PKR" },
  { label: "Rúpias de Seicheles", value: "SCR" },
  { label: "Shilling Queniano", value: "KES" },
  { label: "Shilling Somaliano", value: "SOS" },
  { label: "Shilling Tanzaniano", value: "TZS" },
  { label: "Shilling Ugandês", value: "UGX" },
  { label: "Sol do Peru", value: "PEN" },
  { label: "Som Quirguistanês", value: "KGS" },
  { label: "Som Uzbequistanês", value: "UZS" },
  { label: "Somoni do Tajiquistão", value: "TJS" },
  { label: "Taka de Bangladesh", value: "BDT" },
  { label: "Tengue Cazaquistanês", value: "KZT" },
  { label: "TMT", value: "TMT" },
  { label: "Vatu de Vanuatu", value: "VUV" },
  { label: "Won Sul-Coreano", value: "KRW" },
  { label: "XRP", value: "XRP" },
  { label: "Yuan Chinês", value: "CNY" },
  { label: "Yuan chinês offshore", value: "CNH" },
  { label: "Zlóti Polonês", value: "PLN" },
];
